### ISSUE TITLE
Numerical computation problem regarding cholesky decomposition.

### ISSUE THREAD

**Issue by WOWNICE** [htdt/self-supervised#1]
Hi thanks for sharing the code! 

I've run into some problems when reimplementing the whitening function. After training for like 10-20 epochs of training, the covariance matrix of the features becomes singular. 

For the sake of simplicity, I will provide the minimal code of my reimplementation here (I noticed that you use "+eps*eye" trick in your code, however this trick doesn't completely solve the singular-matrix problem... ). 
```
# x is N*D feature matrix.
x = x - x.mean(dim=0)
x_cov = torch.matmul(x.T, x) / (x.shape[0] -1)

# eps * eye 
x_cov = (1-self.eps) * x_cov + self.eps * torch.eye(x.shape[1]).cuda()

L = torch.cholesky(x_cov)
W = torch.inverse(L).T
```

And the error message looks like:
**RuntimeError: cholesky_cuda: U(254,254) is zero, singular U.**

Is there any good measure of preventing this error? Thanks a lot!

**Comment by WOWNICE** [comment]
I fix this problem by setting eps=1e-4 instead of eps=1e-6. However I don't know whether adding such value of the identity matrix would change a "covariance matrix" to some other things. Issue closed.

**Comment by htdt** [comment]
Indeed, adding this epsilon stabilizes the computation. However, in all my experiments I used eps = 0, it was not needed. In some cases I had this error, but it always indicated some mistake / incorrect hyperparameters that broke the representation and consequently we could not compute the decomposition.

**Comment by jeroenmollink** [comment]
Very interesting work, thanks for sharing the code. 

I ran into the same error when having eps = 0. Setting eps=1e-4 seems to work for most batches, but occasionally it throws the same error again. Could you elaborate on what mistake specifically/incorrect hyperparameters you fixed when you encountered this error?

**Comment by htdt** [comment]
> what mistake specifically/incorrect hyperparameters

Nothing special really, during development there are many possible configurations iterated and some of them just do not work. E.g. we recently ran an ablation where we combined contrastive loss and whitening and in this case we observed divergence resulting this error.

**Comment by jianlong-yuan** [comment]
Same error. Any news? How to fix this error?

**Comment by xuChenSJTU** [comment]
Hi，I have the same error when implementing wmse using DistributedDataParallel in pytorch on Imagenet100...
Is there any update now? How to fix this problem? @htdt @jianlong-yuan @WOWNICE @jeroenmollink @AliaksandrSiarohin

**Comment by seobbro** [comment]
Hi, I had the same error, but I think it's due to the batch size. 
If I run this code with a low batch size, you should use w_eps>=1e-4 so that the error does not happen. 
(The minimum w_eps varies with different datasets.)

**Comment by ibarrien** [comment]
> Indeed, adding this epsilon stabilizes the computation. However, in all my experiments I used eps = 0, it was not needed. In some cases I had this error, but it always indicated some mistake / incorrect hyperparameters that broke the representation and consequently we could not compute the decomposition.

@htdt : thank you for this neat work + repo. If eps = 0 is used to reproduce the results in the paper, how should we interpret the "instability" issues (associated with the covariance matrices) mentioned in the paper?
E.g. if eps = 0 is sufficient to reproduce the paper's experiments, what might be a good way to interpret the following comment in the Batch Slicing section: "...this prevents instability issues when computing the covariance matrices."
