### ISSUE TITLE
how to get the tiny imagenet dataset?

### ISSUE THREAD

**Issue by xuChenSJTU** [htdt/self-supervised#3]
Hi,

Thanks for sharing the codes. Could you tell me how to get the tiny-imagenet dataset?

Thanks.

**Comment by htdt** [comment]
Hi, details are here https://github.com/htdt/self-supervised#imagenet-100

**Comment by htdt** [comment]
Hi, you can download it here http://cs231n.stanford.edu/tiny-imagenet-200.zip
