### ISSUE TITLE
Distributed Data Parallel Training on Imagenet?

### ISSUE THREAD

**Issue by xuChenSJTU** [htdt/self-supervised#7]
Hi,

Thanks for sharing the codes. Considering the special approach of solving the covariance matrix, does this method support distributed parallel training? If it does, how about the w_size hyper-parameter? I found an error with batch size=256, 4 gpus (which means each gpu has a batch=64): 

RuntimeError: cholesky_cuda: U(64,64) is zero, singular U.

How to deal with this? Could you give me some advice?

Thank you very much.

**Comment by htdt** [comment]
Hi @xuChenSJTU , 64 sub-batch is too small, from my experience the optimal size should be 2x of the embedding dim, in this case it's 128. I think it's possible to gather embeddings from all GPUs and then apply whitening, although current code does not support this.
